/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 statue.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Statue(props) {
  const { nodes, materials } = useGLTF('/models/statue.glb')
  return (
    <group {...props} dispose={null} castShadow>
      <mesh castShadow geometry={nodes.Venus.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} scale={0.28} />
    </group>
  )
}

useGLTF.preload('/models/statue.glb')
